service: aragonjairus
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

resources:
  - ${file(resources/s3.yml)}
  - ${file(resources/cloudfront.yml)}
  - ${file(resources/codebuild.yml)}
  - ${file(resources/codepipeline.yml)}

plugins:
  - serverless-parameters

custom:
  parameters:
    GithubOwner:
      Type: String
      Default: ${file(config.${opt:stage, 'dev'}.json):GithubOwner}
    GithubRepo:
      Type: String
      Default: ${file(config.${opt:stage, 'dev'}.json):GithubRepo}
    GithubOAuthToken:
      Type: String
      Default: ${file(config.${opt:stage, 'dev'}.json):GithubOAuthToken}
