Resources:
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - ${file(config.${opt:stage, 'dev'}.json):CloudFrontAlias}
        ViewerCertificate:
          SslSupportMethod: "sni-only"
          AcmCertificateArn: ${file(config.${opt:stage, 'dev'}.json):CloudFrontAcmCertificateArn}
        Origins:
          - DomainName: !GetAtt SiteBucket.DomainName
            Id: !Ref SiteBucket
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          MinTTL: 86400
          MaxTTL: 31536000
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref SiteBucket
          ViewerProtocolPolicy: "allow-all"
