Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  CodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties: {}
